# Generated by Django 4.0.2 on 2022-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_did_you_come_to_the_policestation', models.CharField(max_length=100)),
                ('waiting_time', models.CharField(max_length=30)),
                ('overall', models.IntegerField(choices=[(1, 'very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')], default=3)),
                ('behaviour', models.IntegerField(choices=[(1, 'very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')], default=3)),
                ('servicing', models.IntegerField(choices=[(1, 'very bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')], default=3)),
                ('type_feedback', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=30)),
                ('police_name', models.CharField(max_length=50, null=True)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
