# Generated by Django 4.0.2 on 2022-10-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='verification',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type_feedback',
            field=models.CharField(choices=[(1, 'positive'), (2, 'negative')], default=1, max_length=11),
        ),
    ]
