# Generated by Django 4.0.2 on 2022-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_verificationcodes_delete_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type_feedback',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative')], default=1, max_length=11),
        ),
    ]
