# Generated by Django 3.2.9 on 2022-10-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_feedback_type_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='how_did_you_come_to_the_policestation',
        ),
        migrations.AddField(
            model_name='feedback',
            name='reason_to_come',
            field=models.CharField(max_length=100, null=True, verbose_name='how_did_you_come_to_the_policestation'),
        ),
    ]
